# Introduction
The *Analysis of Climate Data Application* (ACD-App) has been developed under the SASSCAL initiative (http://www.sasscal.org) through the Climate Task *Historical and ongoing climate data management* to facilitate the visualization of climate data in the meteorological services of Angola, Botswana and Zambia.

The App was conceived to facilitate the interaction with climate data stored in CLIMSOFT (<http://www.climsoft.org>), a Climate Data Management System (CDMS) developed in Africa and installed in the meteorological services of the SASSCAL countries. This App has been improved over the years so that it currently allows the interaction with climate data stored in ASCII files and create several climatic products.

The App provides specific features depending on the data source the user is working with (either CLIMSOFT or a local file)

The tool has been developed under Shiny, an open source R package that provides a powerful web framework for building web applications using R (<https://shiny.rstudio.com/>). Shiny helps turn data analyses into interactive web applications without requiring HTML, CSS, or JavaScript knowledge ([RStudio, 2017](#references))

This manual will give an overview of the Application, explaining how to install it, how to run it and how to use it. 


